version: '3.1'
services:
  zeppelin:
    image: apache/zeppelin:0.10.0
    volumes:
      - ./logs:/logs
      - ./notebook:/notebook
    ports:
      - "8888:8080"
    environment:
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
